name: iosApp
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - iosApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.tabakpp.ios
      DEVELOPMENT_TEAM: "" # You'll fill this or leave for AltStore to override
    dependencies:
      - framework: ../shared/build/XCFrameworks/release/sharedKit.xcframework
        embed: true
